package voiceml

import (
	"context"
	"net/url"
)

// IncomingPhoneNumbersService is the /IncomingPhoneNumbers resource group —
// CRUD on the DIDs assigned to the authenticated tenant.
type IncomingPhoneNumbersService struct{ c *Client }

// IncomingPhoneNumberCapabilities is the channel-capability sub-object on an
// IncomingPhoneNumber. VoiceML is voice-only, so on responses generated by
// the VoiceML server `Voice` will be true and the rest false — the fields
// are present to match Twilio's wire shape so strict-binding consumers don't
// throw on deserialize.
type IncomingPhoneNumberCapabilities struct {
	Voice bool `json:"voice"`
	SMS   bool `json:"sms"`
	MMS   bool `json:"mms"`
	Fax   bool `json:"fax"`
}

// IncomingPhoneNumber is a Twilio-shape IncomingPhoneNumber resource. `Sid`
// is the canonical PN-prefixed opaque identifier; `PhoneNumber` carries the
// E.164 form. Nullable / often-empty Twilio-compat fields are exposed as
// `*string` so callers can distinguish "server emitted empty string" from
// "field absent in this response".
type IncomingPhoneNumber struct {
	Sid          string `json:"sid"`
	AccountSid   string `json:"account_sid"`
	PhoneNumber  string `json:"phone_number"`
	FriendlyName string `json:"friendly_name,omitempty"`
	APIVersion   string `json:"api_version"`
	URI          string `json:"uri"`

	Origin *string `json:"origin,omitempty"`
	Beta   *bool   `json:"beta,omitempty"`

	Capabilities IncomingPhoneNumberCapabilities `json:"capabilities"`

	VoiceURL             *string `json:"voice_url,omitempty"`
	VoiceMethod          *string `json:"voice_method,omitempty"`
	VoiceFallbackURL     *string `json:"voice_fallback_url,omitempty"`
	VoiceFallbackMethod  *string `json:"voice_fallback_method,omitempty"`
	VoiceApplicationSid  *string `json:"voice_application_sid,omitempty"`
	VoiceCallerIDLookup  *bool   `json:"voice_caller_id_lookup,omitempty"`
	VoiceReceiveMode     *string `json:"voice_receive_mode,omitempty"`

	SMSURL              *string `json:"sms_url,omitempty"`
	SMSMethod           *string `json:"sms_method,omitempty"`
	SMSFallbackURL      *string `json:"sms_fallback_url,omitempty"`
	SMSFallbackMethod   *string `json:"sms_fallback_method,omitempty"`
	SMSApplicationSid   *string `json:"sms_application_sid,omitempty"`

	StatusCallback       *string `json:"status_callback,omitempty"`
	StatusCallbackMethod *string `json:"status_callback_method,omitempty"`

	TrunkSid                *string `json:"trunk_sid,omitempty"`
	AddressSid              *string `json:"address_sid,omitempty"`
	AddressRequirements     *string `json:"address_requirements,omitempty"`
	IdentitySid             *string `json:"identity_sid,omitempty"`
	BundleSid               *string `json:"bundle_sid,omitempty"`
	EmergencyStatus         *string `json:"emergency_status,omitempty"`
	EmergencyAddressSid     *string `json:"emergency_address_sid,omitempty"`
	EmergencyAddressStatus  *string `json:"emergency_address_status,omitempty"`

	Status      *string `json:"status,omitempty"`
	DateCreated string  `json:"date_created,omitempty"`
	DateUpdated string  `json:"date_updated,omitempty"`
}

// IncomingPhoneNumbersList is the paginated /IncomingPhoneNumbers list response.
type IncomingPhoneNumbersList struct {
	IncomingPhoneNumbers []IncomingPhoneNumber `json:"incoming_phone_numbers"`

	Page            int    `json:"page"`
	PageSize        int    `json:"page_size"`
	NumPages        *int   `json:"num_pages,omitempty"`
	Total           *int   `json:"total,omitempty"`
	Start           *int   `json:"start,omitempty"`
	End             *int   `json:"end,omitempty"`
	FirstPageURI    string `json:"first_page_uri,omitempty"`
	NextPageURI     string `json:"next_page_uri,omitempty"`
	PreviousPageURI string `json:"previous_page_uri,omitempty"`
	URI             string `json:"uri,omitempty"`
}

// ListIncomingPhoneNumbersParams are the filter / pagination query params for
// GET /IncomingPhoneNumbers. PhoneNumber, when set, is an exact-match E.164
// filter — Twilio's canonical lookup pattern returns a 0-or-1-row envelope.
type ListIncomingPhoneNumbersParams struct {
	PhoneNumber string
	Page        *int
	PageSize    *int
}

func (p ListIncomingPhoneNumbersParams) query() url.Values {
	v := url.Values{}
	setString(v, "PhoneNumber", p.PhoneNumber)
	setIntP(v, "Page", p.Page)
	setIntP(v, "PageSize", p.PageSize)
	return v
}

// CreateIncomingPhoneNumberParams is the body for POST /IncomingPhoneNumbers.
// PhoneNumber is required and must be E.164 (leading `+`, 7-15 digits). The
// endpoint is idempotent on the same tenant — re-POSTing the same PhoneNumber
// rebinds its voice routing without erroring; returns 409 when the number is
// already claimed by a different account.
type CreateIncomingPhoneNumberParams struct {
	PhoneNumber         string  `form:"PhoneNumber"`
	VoiceURL            *string `form:"VoiceUrl"`
	VoiceMethod         *string `form:"VoiceMethod"`
	VoiceFallbackURL    *string `form:"VoiceFallbackUrl"`
	VoiceFallbackMethod *string `form:"VoiceFallbackMethod"`
}

func (p CreateIncomingPhoneNumberParams) form() url.Values {
	v := url.Values{}
	v.Set("PhoneNumber", p.PhoneNumber)
	setStringP(v, "VoiceUrl", p.VoiceURL)
	setStringP(v, "VoiceMethod", p.VoiceMethod)
	setStringP(v, "VoiceFallbackUrl", p.VoiceFallbackURL)
	setStringP(v, "VoiceFallbackMethod", p.VoiceFallbackMethod)
	return v
}

// UpdateIncomingPhoneNumberParams is the body for
// POST /IncomingPhoneNumbers/{sid}. Only-set-fields-touched semantics.
type UpdateIncomingPhoneNumberParams struct {
	VoiceURL            *string `form:"VoiceUrl"`
	VoiceMethod         *string `form:"VoiceMethod"`
	VoiceFallbackURL    *string `form:"VoiceFallbackUrl"`
	VoiceFallbackMethod *string `form:"VoiceFallbackMethod"`
}

func (p UpdateIncomingPhoneNumberParams) form() url.Values {
	v := url.Values{}
	setStringP(v, "VoiceUrl", p.VoiceURL)
	setStringP(v, "VoiceMethod", p.VoiceMethod)
	setStringP(v, "VoiceFallbackUrl", p.VoiceFallbackURL)
	setStringP(v, "VoiceFallbackMethod", p.VoiceFallbackMethod)
	return v
}

// List returns the page of DIDs assigned to this tenant.
// GET /IncomingPhoneNumbers. Pass nil for an unfiltered first-page request.
func (s *IncomingPhoneNumbersService) List(ctx context.Context, params *ListIncomingPhoneNumbersParams) (*IncomingPhoneNumbersList, error) {
	var q url.Values
	if params != nil {
		q = params.query()
	}
	var out IncomingPhoneNumbersList
	err := s.c.t.do(ctx, requestOpts{
		method: "GET",
		path:   s.c.pathf("IncomingPhoneNumbers"),
		query:  q,
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Create assigns a DID to the authenticated tenant.
// POST /IncomingPhoneNumbers.
func (s *IncomingPhoneNumbersService) Create(ctx context.Context, params CreateIncomingPhoneNumberParams) (*IncomingPhoneNumber, error) {
	var out IncomingPhoneNumber
	err := s.c.t.do(ctx, requestOpts{
		method: "POST",
		path:   s.c.pathf("IncomingPhoneNumbers"),
		form:   params.form(),
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get fetches a single DID by its PN-prefixed SID.
// GET /IncomingPhoneNumbers/{sid}.
func (s *IncomingPhoneNumbersService) Get(ctx context.Context, sid string) (*IncomingPhoneNumber, error) {
	var out IncomingPhoneNumber
	err := s.c.t.do(ctx, requestOpts{
		method: "GET",
		path:   s.c.pathf("IncomingPhoneNumbers", sid),
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update mutates voice routing on an assigned DID.
// POST /IncomingPhoneNumbers/{sid}. Only-set-fields-touched.
func (s *IncomingPhoneNumbersService) Update(ctx context.Context, sid string, params UpdateIncomingPhoneNumberParams) (*IncomingPhoneNumber, error) {
	var out IncomingPhoneNumber
	err := s.c.t.do(ctx, requestOpts{
		method: "POST",
		path:   s.c.pathf("IncomingPhoneNumbers", sid),
		form:   params.form(),
	}, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete releases a DID from the authenticated tenant.
// DELETE /IncomingPhoneNumbers/{sid}. Idempotent: returns nil on success or
// when the number was already gone.
func (s *IncomingPhoneNumbersService) Delete(ctx context.Context, sid string) error {
	return s.c.t.do(ctx, requestOpts{
		method: "DELETE",
		path:   s.c.pathf("IncomingPhoneNumbers", sid),
	}, nil)
}
