name: Dependency Submission

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  go-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: actions/go-dependency-submission@v2
        with:
          go-mod-path: go.mod
